package io.neuropop.util.regex;

public enum RegexOption {
	UNIX_LINES,
	CASE_INSENSITIVE,
	PERMIT_COMMENTS,
	MULTILINE,
	LITERAL_PARSING,
	DOT_TERMINATORS,
	UNICODE_CASE_FOLDING,
	CANONICAL_EQUIVALENCE,
	UNICODE_CLASSES;
}
